# 1. Extração e Análise Exploratória Inicial

Nesta primeira etapa do pipeline de ETL, realizamos a leitura dos dados brutos a partir do arquivo CSV e executamos a inspeção inicial da estrutura da base de dados (`shape`, `info`, `describe`).

### Objetivos:
- Validar o carregamento dos dados com a codificação (`utf-8`) e separador (`.csv`) corretos.
- Identificar o número total de registros e colunas.
- Mapear a presença de valores nulos e verificar os tipos primitivos de dados lidos pelo Pandas.

In [ ]:
import pandas as pd 
import numpy as np 
import requests
import difflib

df_clientes = pd.read_csv('../data/clientes_distribuidora_vetor.csv', sep=';', encoding='utf-8') #enconding trabalha com caracteres especiais e sep trabalha com o separador do arquivo csv

display(df_clientes.head(14)) #deixa mais visualmente bonito a visualização do dataframe
display (df_clientes.shape) #mostra a quantidade de linhas e colunas do dataframe

display(df_clientes.info()) #mostra informações do dataframe, como quantidade de linhas, colunas, tipos de dados e valores nulos
display(df_clientes.describe()) #mostra estatísticas descritivas do dataframe, como média, mediana, desvio padrão, valores mínimos e máximos

,id_cliente,razao_social,cnpj,telefone,email,bairro_informado,cep,cidade,uf,data_cadastro,vendedor_responsavel
0,CLI0001,Mercadinho Boa Vista,84.959.310/3413-16,61970855700,contato@mercadinhobo.com.br,Sul (Águas Claras),71926-750,Brasília,DF,2022-06-21,Bruno Almeida
1,CLI0002,Comercial São Judas,28.327.648/3503-05,+55 61 95386-2084,contato@comercialsão.com.br,Sul (Aguas Claras),72140-010,Brasília,DF,2023-10-07,Camila Torres
2,CLI0003,Armarinhos Silva & Cia,42.388.496/9653-28,+55 61 92489-1771,contato@armarinhossi.com.br,Taguatinga - DF,72140-010,Brasília,DF,28/02/2022,Camila Torres
3,CLI0004,Empório Vale Verde,69.784.801/8451-46,(61) 98433-1053,contato@empóriovalev.com.br,aguas claras,71929-000,Brasília,DF,"Dec 24, 2023",Diego Martins
4,CLI0005,Mercearia Dois Irmãos,89.325.288/0957-01,61951273847,contato@merceariadoi.com.br,Taguatinga/DF,00000-000,Brasília,DF,08-01-2022,Diego Martins
5,CLI0006,Casa das Tintas Ipê,82.278.248/9638-34,+55 61 97118-8177,contato@casadastinta.com.br,Águas Claras,NaN,Brasília,DF,2021-08-17,Camila Torres
6,CLI0007,Distribuidora Popular Centro-Oeste,83.930.103/1051-83,61999788677,contato@distribuidor.com.br,TAGUATINGA,NaN,Brasília,DF,2025-04-16,Camila Torres
7,CLI0008,Bazar Estrela Dourada,31.165.667/0106-51,(61) 94139-4116,contato@bazarestrela.com.br,V. Pires,72006-400,Brasília,DF,"Aug 18, 2022",Juliana Reis
8,CLI0009,Supermercado Nova Aliança,10.801.326/7736-02,+55 61 91035-7396,contato@supermercado.com.br,Aguas claras,71926-750,Brasília,DF,2023-08-09,Juliana Reis
9,CLI0010,Papelaria Horizonte,34.309.805/0097-88,(61) 91931-9320,contato@papelariahor.com.br,Águas Claras/DF,71950-000,Brasília,DF,03/03/2021,Diego Martins
10,CLI0011,Ferragens União,93.990.916/9985-43,61942035886,contato@ferragensuni.com.br,Vicente Pires,72006-400,Brasília,DF,2022-07-09,Bruno Almeida
11,CLI0012,Mercado Cantinho do Sabor,79.911.838/4251-35,61931172421,contato@mercadocanti.com.br,Aguas Claras - DF,71950-000,Brasília,DF,2023-09-15,Diego Martins
12,CLI0013,Loja Fatima Confecções,24.118.244/9353-48,+55 61 95114-1832,contato@lojafatimaco.com.br,guara - df,NaN,Brasília,DF,2024-11-03,Bruno Almeida
13,CLI0014,Depósito São Roque,27868011280598,(61) 98041-3088,contato@depósitosãor.com.br,Taguatinga,NaN,Brasília,DF,02-05-2023,Rafael Souza

(47, 11)

<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_cliente            47 non-null     str
 1   razao_social          47 non-null     str
 2   cnpj                  47 non-null     str
 3   telefone              47 non-null     str
 4   email                 47 non-null     str
 5   bairro_informado      46 non-null     str
 6   cep                   34 non-null     str
 7   cidade                47 non-null     str
 8   uf                    47 non-null     str
 9   data_cadastro         47 non-null     str
 10  vendedor_responsavel  47 non-null     str
dtypes: str(11)
memory usage: 4.2 KB

None

,id_cliente,razao_social,cnpj,telefone,email,bairro_informado,cep,cidade,uf,data_cadastro,vendedor_responsavel
count,47,47,47,47,47,46,34,47,47,47,47
unique,47,47,47,47,44,25,15,1,1,47,5
top,CLI0001,Mercadinho Boa Vista,84.959.310/3413-16,61970855700,contato@distribuidor.com.br,Aguas claras,72140-010,Brasília,DF,2022-06-21,Camila Torres
freq,1,1,1,1,4,4,4,47,47,1,14

### 2. Transformação e Limpeza de Dados (ETL)

Nesta etapa do pipeline, tratamos as inconsistências e os ruídos encontrados na base de dados bruta da Distribuidora Vetor, preparando os campos para análises agregadas confiáveis.

### Principais Frentes de Atuação:
- **Campos Cadastrais (CNPJ, Telefones e CEP):** Remoção de caracteres especiais (pontos, barras, traços, parênteses e espaços) e do DDI (`+55`/`55`) do início dos telefones para padronizar os dados em formatos limpos.
- **Data de Cadastro:** Conversão de múltiplos formatos misturados (ISO, padrão brasileiro e texto) para o tipo data padrão, tratando falhas de conversão.
- **Normalização Textual de Bairros:** Aplicação de limpeza de texto (minúsculas, remoção de acentos e espaços extras) e estruturação de um dicionário "De-Para" para unificar grafias divergentes.
- **Tratamento de Nulos:** Identificação e substituição de valores ausentes em campos essenciais como `bairro_informado` e `cep` pelo rótulo `"Não informado"`.

**Resumo da etapa:** Limpeza de caracteres especiais e remoção do DDI (`+55`) nas colunas `telefone`, `cnpj` e `cep` aplicadas diretamente nas colunas principais, tratamento dos valores nulos nas colunas `bairro_informado` e `cep` (substituindo por `"Não informado"`), e conversão da coluna `data_cadastro` para o formato `datetime` na cópia de trabalho (`df_analise`).

In [104]:
display(df_clientes['cnpj']) # coluna cnpj do dataframe


# remove o '+55' ou '55' apenas se estiver no início da linha
df_clientes['telefone'] = df_clientes['telefone'].astype(str).str.replace(r'^\+?55', '', regex=True)

# remove caracteres não numéricos da coluna cnpj e cria uma nova coluna
df_clientes['telefone'] = df_clientes['telefone'].str.replace(r'\D', '', regex=True) 
df_clientes['cnpj'] = df_clientes['cnpj'].str.replace(r'\D', '', regex=True)  
df_clientes['cep'] = df_clientes['cep'].str.replace(r'\D', '', regex=True) 

df_analise = df_clientes.copy() # cria uma cópia do dataframe df_clientes para df_analise para realizar as transformações

# substitui os valores nulos da coluna bairro_informado por 'Não informado' usando o método fillna()
df_analise['cep'] = df_analise['cep'].fillna('Não informado') 
df_analise['bairro_informado'] = df_analise['bairro_informado'].fillna('Não informado') 

# converte datas de formatos mistos (meses em texto como dec/aug, barras e ISO) para o padrão ISO (AAAA-MM-DD) do SQLite e Django
df_analise['data_cadastro'] = pd.to_datetime(df_analise['data_cadastro'], format='mixed', dayfirst=True, errors='coerce')

display(df_analise['data_cadastro'].unique()) # exibe os valores únicos da data_cadastro para confirmar que ficaram no formato correto

display(df_analise.head(10)) # ou simplesmente escrever o nome da variável na última linha da célula: df_analise

df_analise.info() # mostra informações do dataframe df_analise para confirmar que o valor nulo foi tratado

0     84.959.310/3413-16
1     28.327.648/3503-05
2     42.388.496/9653-28
3     69.784.801/8451-46
4     89.325.288/0957-01
5     82.278.248/9638-34
6     83.930.103/1051-83
7     31.165.667/0106-51
8     10.801.326/7736-02
9     34.309.805/0097-88
10    93.990.916/9985-43
11    79.911.838/4251-35
12    24.118.244/9353-48
13        27868011280598
14    69.232.260/2563-42
15        36541458685014
16    93.406.088/3561-59
17    82.366.299/4680-44
18        48951343320037
19    20.163.287/0831-72
20    77.434.873/4714-34
21        66587603669096
22        34670656272980
23    37.556.464/1708-05
24        27193745299124
25        49190586518506
26    87.769.453/1473-79
27    49.480.831/3678-37
28    85.685.574/4431-35
29    34.352.408/2400-84
30    04.711.671/9022-94
31    74.964.990/9133-41
32    03.447.134/9361-83
33    17.464.887/7190-65
34    02.787.429/6717-56
35    07.154.516/8087-60
36    10.932.480/8613-17
37    78.263.982/1465-84
38    58.867.533/9636-05
39    71.870.262/1745-96
40    13.431.611/7240-05
41        19693792374740
42    43.671.369/5944-06
43        53394210470952
44    47.451.712/3685-16
45    37.098.593/1746-12
46    82.675.869/2617-96
Name: cnpj, dtype: str

<DatetimeArray>
['2022-06-21 00:00:00', '2023-07-10 00:00:00', '2022-02-28 00:00:00',
 '2023-12-24 00:00:00', '2022-01-08 00:00:00', '2021-08-17 00:00:00',
 '2025-04-16 00:00:00', '2022-08-18 00:00:00', '2023-09-08 00:00:00',
 '2021-03-03 00:00:00', '2022-09-07 00:00:00', '2023-09-15 00:00:00',
 '2024-03-11 00:00:00', '2023-05-02 00:00:00', '2022-08-28 00:00:00',
 '2024-04-10 00:00:00', '2023-02-28 00:00:00', '2024-08-15 00:00:00',
 '2025-07-15 00:00:00', '2025-08-25 00:00:00', '2022-02-18 00:00:00',
 '2024-10-07 00:00:00', '2022-07-21 00:00:00', '2022-01-25 00:00:00',
 '2024-10-10 00:00:00', '2024-12-11 00:00:00', '2024-11-01 00:00:00',
 '2022-05-03 00:00:00', '2022-12-25 00:00:00', '2025-01-28 00:00:00',
 '2025-07-18 00:00:00', '2022-01-03 00:00:00', '2025-04-03 00:00:00',
 '2022-02-22 00:00:00', '2024-08-20 00:00:00', '2023-12-16 00:00:00',
 '2025-10-27 00:00:00', '2022-11-22 00:00:00', '2025-11-28 00:00:00',
 '2022-12-07 00:00:00', '2024-02-06 00:00:00', '2021-11-19 00:00:00',
 '2022-07-24 00:00:00', '2023-08-04 00:00:00', '2021-02-16 00:00:00',
 '2022-06-23 00:00:00']
Length: 46, dtype: datetime64[us]

,id_cliente,razao_social,cnpj,telefone,email,bairro_informado,cep,cidade,uf,data_cadastro,vendedor_responsavel
0,CLI0001,Mercadinho Boa Vista,84959310341316,61970855700,contato@mercadinhobo.com.br,Sul (Águas Claras),71926750,Brasília,DF,2022-06-21,Bruno Almeida
1,CLI0002,Comercial São Judas,28327648350305,61953862084,contato@comercialsão.com.br,Sul (Aguas Claras),72140010,Brasília,DF,2023-07-10,Camila Torres
2,CLI0003,Armarinhos Silva & Cia,42388496965328,61924891771,contato@armarinhossi.com.br,Taguatinga - DF,72140010,Brasília,DF,2022-02-28,Camila Torres
3,CLI0004,Empório Vale Verde,69784801845146,61984331053,contato@empóriovalev.com.br,aguas claras,71929000,Brasília,DF,2023-12-24,Diego Martins
4,CLI0005,Mercearia Dois Irmãos,89325288095701,61951273847,contato@merceariadoi.com.br,Taguatinga/DF,00000000,Brasília,DF,2022-01-08,Diego Martins
5,CLI0006,Casa das Tintas Ipê,82278248963834,61971188177,contato@casadastinta.com.br,Águas Claras,Não informado,Brasília,DF,2021-08-17,Camila Torres
6,CLI0007,Distribuidora Popular Centro-Oeste,83930103105183,61999788677,contato@distribuidor.com.br,TAGUATINGA,Não informado,Brasília,DF,2025-04-16,Camila Torres
7,CLI0008,Bazar Estrela Dourada,31165667010651,61941394116,contato@bazarestrela.com.br,V. Pires,72006400,Brasília,DF,2022-08-18,Juliana Reis
8,CLI0009,Supermercado Nova Aliança,10801326773602,61910357396,contato@supermercado.com.br,Aguas claras,71926750,Brasília,DF,2023-09-08,Juliana Reis
9,CLI0010,Papelaria Horizonte,34309805009788,61919319320,contato@papelariahor.com.br,Águas Claras/DF,71950000,Brasília,DF,2021-03-03,Diego Martins

<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_cliente            47 non-null     str
 1   razao_social          47 non-null     str
 2   cnpj                  47 non-null     str
 3   telefone              47 non-null     str
 4   email                 47 non-null     str
 5   bairro_informado      47 non-null     str
 6   cep                   47 non-null     str
 7   cidade                47 non-null     str
 8   uf                    47 non-null     str
 9   data_cadastro         47 non-null     datetime64[us]
 10  vendedor_responsavel  47 non-null     str
dtypes: datetime64[us](1), str(10)
memory usage: 4.2 KB

### 🧹 Padronização de Texto (`bairro_informado`)

Nesta etapa, aplicamos transformações de string na coluna `bairro_informado` para garantir a consistência e limpeza dos dados antes do mapeamento:

- **Remoção de Espaços (`.str.strip()`):** Elimina espaços em branco indesejados no início e no final do texto.
- **Padronização de Caixa (`.str.title()`):** Converte a primeira letra de cada palavra em maiúscula e as demais em minúscula (ex: `"aguas claras"` vira `"Aguas Claras"`).
- **Validação Estrutural:** Exibe o DataFrame atualizado e as informações técnicas (`.info()`) para confirmar que as alterações foram aplicadas corretamente.

In [105]:
# remove espaços em branco no início e no final da string
df_analise['bairro_informado'] = df_analise['bairro_informado'].str.strip() 

# converte a primeira letra de cada palavra para maiúscula e as demais para minúscula
df_analise['bairro_informado'] = df_analise['bairro_informado'].str.title() 

display(df_analise) 
display(df_analise.info())

,id_cliente,razao_social,cnpj,telefone,email,bairro_informado,cep,cidade,uf,data_cadastro,vendedor_responsavel
0,CLI0001,Mercadinho Boa Vista,84959310341316,61970855700,contato@mercadinhobo.com.br,Sul (Águas Claras),71926750,Brasília,DF,2022-06-21,Bruno Almeida
1,CLI0002,Comercial São Judas,28327648350305,61953862084,contato@comercialsão.com.br,Sul (Aguas Claras),72140010,Brasília,DF,2023-07-10,Camila Torres
2,CLI0003,Armarinhos Silva & Cia,42388496965328,61924891771,contato@armarinhossi.com.br,Taguatinga - Df,72140010,Brasília,DF,2022-02-28,Camila Torres
3,CLI0004,Empório Vale Verde,69784801845146,61984331053,contato@empóriovalev.com.br,Aguas Claras,71929000,Brasília,DF,2023-12-24,Diego Martins
4,CLI0005,Mercearia Dois Irmãos,89325288095701,61951273847,contato@merceariadoi.com.br,Taguatinga/Df,00000000,Brasília,DF,2022-01-08,Diego Martins
5,CLI0006,Casa das Tintas Ipê,82278248963834,61971188177,contato@casadastinta.com.br,Águas Claras,Não informado,Brasília,DF,2021-08-17,Camila Torres
6,CLI0007,Distribuidora Popular Centro-Oeste,83930103105183,61999788677,contato@distribuidor.com.br,Taguatinga,Não informado,Brasília,DF,2025-04-16,Camila Torres
7,CLI0008,Bazar Estrela Dourada,31165667010651,61941394116,contato@bazarestrela.com.br,V. Pires,72006400,Brasília,DF,2022-08-18,Juliana Reis
8,CLI0009,Supermercado Nova Aliança,10801326773602,61910357396,contato@supermercado.com.br,Aguas Claras,71926750,Brasília,DF,2023-09-08,Juliana Reis
9,CLI0010,Papelaria Horizonte,34309805009788,61919319320,contato@papelariahor.com.br,Águas Claras/Df,71950000,Brasília,DF,2021-03-03,Diego Martins
10,CLI0011,Ferragens União,93990916998543,61942035886,contato@ferragensuni.com.br,Vicente Pires,72006400,Brasília,DF,2022-09-07,Bruno Almeida
11,CLI0012,Mercado Cantinho do Sabor,79911838425135,61931172421,contato@mercadocanti.com.br,Aguas Claras - Df,71950000,Brasília,DF,2023-09-15,Diego Martins
12,CLI0013,Loja Fatima Confecções,24118244935348,61951141832,contato@lojafatimaco.com.br,Guara - Df,Não informado,Brasília,DF,2024-03-11,Bruno Almeida
13,CLI0014,Depósito São Roque,27868011280598,61980413088,contato@depósitosãor.com.br,Taguatinga,Não informado,Brasília,DF,2023-05-02,Rafael Souza
14,CLI0015,Comercial Rio Bonito,69232260256342,6134911634,contato@comercialrio.com.br,Aguas Claras,71926750,Brasília,DF,2022-08-28,Camila Torres
15,CLI0016,Minimercado Vitória Régia,36541458685014,61953491626,contato@minimercadov.com.br,Vicente Pires - Df,72006400,Brasília,DF,2024-04-10,Bruno Almeida
16,CLI0017,Casa de Carnes Ouro Fino,93406088356159,61999038359,contato@casadecarnes.com.br,Vte Pires,72110800,Brasília,DF,2023-02-28,Diego Martins
17,CLI0018,Armazém Planalto,82366299468044,61980436279,contato@armazémplana.com.br,Vte Pires,72006530,Brasília,DF,2024-08-15,Camila Torres
18,CLI0019,Bazar Flor de Lis,48951343320037,6139702193,contato@bazarflordel.com.br,Guará Ii,Não informado,Brasília,DF,2025-07-15,Camila Torres
19,CLI0020,Mercado Bom Preço DF,20163287083172,61997026198,contato@mercadobompr.com.br,Taguatinga - Df,72130010,Brasília,DF,2025-08-25,Diego Martins
20,CLI0021,Distribuidora Cerrado Norte,77434873471434,61952910691,contato@distribuidor.com.br,Taguatinga Sul,72140010,Brasília,DF,2022-02-18,Camila Torres
21,CLI0022,Comercial Águas do Sul,66587603669096,61910966763,contato@comercialágu.com.br,Taguatinga,72110010,Brasília,DF,2024-10-07,Diego Martins
22,CLI0023,Padaria Trigo Dourado,34670656272980,61914442375,contato@padariatrigo.com.br,Taguatinga - Df,72140010,Brasília,DF,2022-07-21,Juliana Reis
23,CLI0024,Loja de Utilidades Girassol,37556464170805,61921241659,contato@lojadeutilid.com.br,Sul (Águas Claras),Não informado,Brasília,DF,2022-01-25,Camila Torres
24,CLI0025,Empório do Produtor,27193745299124,6136921420,contato@empóriodopro.com.br,Taguatinga/Df,Não informado,Brasília,DF,2024-10-10,Juliana Reis
25,CLI0026,Mercadinho Recanto Feliz,49190586518506,61927298102,contato@mercadinhore.com.br,Vicente Pires,Não informado,Brasília,DF,2024-12-11,Camila Torres
26,CLI0027,Casa da Limpeza Total,87769453147379,6137847209,contato@casadalimpez.com.br,Guará I,Não informado,Brasília,DF,2024-11-01,Bruno Almeida
27,CLI0028,Comercial Serra Azul,49480831367837,61983421282,contato@comercialser.com.br,Aguas Claras,71900100,Brasília,DF,2022-05-03,Juliana Reis
28,CLI0029,Armazém Fazendinha,85685574443135,6138609779,contato@armazémfazen.com.br,Águas Claras Sul,71900000,Brasília,DF,2022-12-25,Camila Torres
29,CLI0030,Bazar Nova Esperança,34352408240084,61990422680,contato@bazarnovaesp.com.br,Norte (Águas Claras),71901010,Brasília,DF,2025-01-28,Bruno Almeida
30,CLI0031,Distribuidora Vale do Alvorada,04711671902294,6133542940,contato@distribuidor.com.br,Guará I,Não informado,Brasília,DF,2025-07-18,Diego Martins
31,CLI0032,Mercearia Central DF,74964990913341,61949293847,contato@merceariacen.com.br,Aguas Claras,71950000,Brasília,DF,2022-02-18,Rafael Souza
32,CLI0033,Loja Bom Retiro,03447134936183,61953523330,contato@lojabomretir.com.br,Vicente Pires - Df,72110800,Brasília,DF,2022-01-03,Bruno Almeida
33,CLI0034,Comercial Duas Palmeiras,17464887719065,6133561423,contato@comercialdua.com.br,Guará Ii,Não informado,Brasília,DF,2025-04-03,Diego Martins
34,CLI0035,Casa das Bebidas Real,02787429671756,61953091709,contato@casadasbebid.com.br,Águas Claras,71925000,Brasília,DF,2022-02-22,Bruno Almeida
35,CLI0036,Mercadinho Nossa Senhora,07154516808760,61994946927,contato@mercadinhono.com.br,Taguatinga Sul,72130010,Brasília,DF,2024-08-20,Rafael Souza
36,CLI0037,Armarinhos Ponto Certo,10932480861317,6137633522,contato@armarinhospo.com.br,Aguas Claras,71929000,Brasília,DF,2023-12-16,Diego Martins
37,CLI0038,Empório Chão Vermelho,78263982146584,6133895891,contato@empóriochãov.com.br,Vte Pires,72006530,Brasília,DF,2025-10-27,Juliana Reis
38,CLI0039,Distribuidora Horizonte Azul,58867533963605,61972467325,contato@distribuidor.com.br,Aguas Claras,00000000,Brasília,DF,2022-11-22,Juliana Reis
39,CLI0040,Casa de Materiais Rocha,71870262174596,6139726383,contato@casademateri.com.br,Águas Claras,00000000,Brasília,DF,2025-11-28,Juliana Reis
40,CLI0041,Mercado Popular Central,13431611724005,6134006873,contato@mercadopopul.com.br,Norte (Aguas Claras),71901010,Brasília,DF,2022-12-07,Camila Torres
41,CLI0042,Comercial Passo Firme,19693792374740,61957129955,contato@comercialpas.com.br,Águas Claras Norte,71906500,Brasília,DF,2024-02-06,Bruno Almeida
42,CLI0043,Bazar Sol Nascente,43671369594406,61911086890,contato@bazarsolnasc.com.br,Águas Claras Norte,71901010,Brasília,DF,2021-11-19,Diego Martins
43,CLI0044,Depósito Cerrado Sul,53394210470952,6134026352,contato@depósitocerr.com.br,Águas Claras/Df,71900100,Brasília,DF,2022-07-24,Camila Torres
44,CLI0045,Loja Multi Utilidades,47451712368516,6133709791,contato@lojamultiuti.com.br,Aguas Claras,71900100,Brasília,DF,2023-08-04,Bruno Almeida
45,CLI0046,Armazém Boa Colheita,37098593174612,6131385986,contato@armazémboaco.com.br,Guará Ii,Não informado,Brasília,DF,2021-02-16,Camila Torres
46,CLI0047,Mercadinho Sem Endereço Completo,82675869261796,61914391105,contato@semendereco.com.br,Não Informado,Não informado,Brasília,DF,2022-06-23,Juliana Reis

<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_cliente            47 non-null     str
 1   razao_social          47 non-null     str
 2   cnpj                  47 non-null     str
 3   telefone              47 non-null     str
 4   email                 47 non-null     str
 5   bairro_informado      47 non-null     str
 6   cep                   47 non-null     str
 7   cidade                47 non-null     str
 8   uf                    47 non-null     str
 9   data_cadastro         47 non-null     datetime64[us]
 10  vendedor_responsavel  47 non-null     str
dtypes: datetime64[us](1), str(10)
memory usage: 4.2 KB

None

### 🏙️ Padronização Avançada e Mapeamento de Bairros

Nesta etapa, consolidamos a limpeza da coluna `bairro_informado` utilizando um dicionário de correspondências para unificar todas as variações encontradas:

- **Limpeza Prévia:** Conversão dos dados para string, remoção de espaços extras nas pontas (`.str.strip()`) e padronização das iniciais em maiúsculas (`.str.title()`).
- **Dicionário de Mapeamento (`mapeamentoBairros`):** Agrupamento e correção de variações de digitação, ausência de acentos, abreviações (ex: `V. Pires`) e sufixos regionais (como `- Df`, `/Df` e indicações de Norte/Sul) para os nomes oficiais consolidados.
- **Validação Final:** Execução do `.unique()` para conferir se restou alguma inconsistência e exibição das primeiras linhas do DataFrame (`df_analise.head(10)`) com todas as informações atualizadas.

In [106]:
# 1. Limpeza básica: transforma tudo em string, remove espaços extras e padroniza as iniciais
df_analise['bairro_informado'] = df_analise['bairro_informado'].astype(str).str.strip().str.title()

# 2. Seu dicionário de mapeamento (ajustado para o padrão do .title() que deixa o 'f' de Df minúsculo)
mapeamentoBairros = {
    "Aguas Claras": "Águas Claras",
    "Águas Claras": "Águas Claras",
    "Águas Claras/Df": "Águas Claras",
    "Aguas Claras - Df": "Águas Claras",
    "Águas Claras Norte": "Águas Claras",
    "Norte (Aguas Claras)": "Águas Claras",
    "Águas Claras Sul": "Águas Claras",
    "Sul (Águas Claras)": "Águas Claras",
    "Sul (Aguas Claras)": "Águas Claras",
    "Norte (Águas Claras)": "Águas Claras",

    "Taguatinga": "Taguatinga",
    "Taguatinga - Df": "Taguatinga",
    "Taguatinga Sul": "Taguatinga",
    "Taguatinga/Df": "Taguatinga",

    "Vicente Pires": "Vicente Pires",
    "Vicente Pires - Df": "Vicente Pires",
    "Vte Pires": "Vicente Pires",
    "V. Pires": "Vicente Pires",

    "Guará Ii": "Guará II",
    "Guara I": "Guará I",
    "Guara - Df": "Guará I",
}

# 3. Aplica a substituição
df_analise['bairro_informado'] = df_analise['bairro_informado'].replace(mapeamentoBairros) 

# 4. Exibe os valores únicos para você conferir se limpou tudo
display(df_analise['bairro_informado'].unique())

display(df_analise.head(10))

<StringArray>
[ 'Águas Claras',    'Taguatinga', 'Vicente Pires',       'Guará I',
      'Guará II', 'Não Informado']
Length: 6, dtype: str

,id_cliente,razao_social,cnpj,telefone,email,bairro_informado,cep,cidade,uf,data_cadastro,vendedor_responsavel
0,CLI0001,Mercadinho Boa Vista,84959310341316,61970855700,contato@mercadinhobo.com.br,Águas Claras,71926750,Brasília,DF,2022-06-21,Bruno Almeida
1,CLI0002,Comercial São Judas,28327648350305,61953862084,contato@comercialsão.com.br,Águas Claras,72140010,Brasília,DF,2023-07-10,Camila Torres
2,CLI0003,Armarinhos Silva & Cia,42388496965328,61924891771,contato@armarinhossi.com.br,Taguatinga,72140010,Brasília,DF,2022-02-28,Camila Torres
3,CLI0004,Empório Vale Verde,69784801845146,61984331053,contato@empóriovalev.com.br,Águas Claras,71929000,Brasília,DF,2023-12-24,Diego Martins
4,CLI0005,Mercearia Dois Irmãos,89325288095701,61951273847,contato@merceariadoi.com.br,Taguatinga,00000000,Brasília,DF,2022-01-08,Diego Martins
5,CLI0006,Casa das Tintas Ipê,82278248963834,61971188177,contato@casadastinta.com.br,Águas Claras,Não informado,Brasília,DF,2021-08-17,Camila Torres
6,CLI0007,Distribuidora Popular Centro-Oeste,83930103105183,61999788677,contato@distribuidor.com.br,Taguatinga,Não informado,Brasília,DF,2025-04-16,Camila Torres
7,CLI0008,Bazar Estrela Dourada,31165667010651,61941394116,contato@bazarestrela.com.br,Vicente Pires,72006400,Brasília,DF,2022-08-18,Juliana Reis
8,CLI0009,Supermercado Nova Aliança,10801326773602,61910357396,contato@supermercado.com.br,Águas Claras,71926750,Brasília,DF,2023-09-08,Juliana Reis
9,CLI0010,Papelaria Horizonte,34309805009788,61919319320,contato@papelariahor.com.br,Águas Claras,71950000,Brasília,DF,2021-03-03,Diego Martins

### 🌐 Enriquecimento de Dados com a API do ViaCEP

Nesta etapa final, integramos o pipeline à API pública do ViaCEP para enriquecer nossa base com os endereços oficiais dos clientes a partir do CEP tratado:

- **Busca Automatizada:** Consulta dos logradouros (ruas, avenidas, alamedas) de forma automática.
- **Otimização de Requisições:** Uso de um dicionário de *cache* contendo apenas os CEPs únicos da base, evitando requisições repetidas e garantindo rapidez na execução.
- **Tratamento de Exceções:** Validação prévia de CEPs ausentes ou fora do formato padrão para evitar erros e lentidão durante as chamadas de rede.

In [107]:
# crio uma função pra buscar o logradouro direto na api dos correios
def consultar_viacep(cep):
    cep_str = str(cep).strip()
    
    # se o cep for inválido nem perco tempo consultando
    if cep_str == 'Não informado' or len(cep_str) != 8:
        return 'Não informado'
    
    url = f"https://viacep.com.br/ws/{cep_str}/json/"
    try:
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            dados = response.json()
            if 'erro' not in dados:
                return dados.get('logradouro', 'Não informado')
    except requests.exceptions.RequestException:
        pass
        
    return 'Não informado'

In [109]:

#remove a coluna caso ela exista no DataFrame, evitando erros se a coluna não estiver presente
df_analise = df_analise.drop(columns=['bairro_api'], errors='ignore')

# pego só os ceps unicos pra não repetir requisição a toa
ceps_unicos = df_analise['cep'].unique()

# crio um cache consultando cada cep único
cache_logradouro = {cep: consultar_viacep(cep) for cep in ceps_unicos}

# jogo o logradouro da api de volta na tabela principal usando o cache
df_analise['logradouro_api'] = df_analise['cep'].map(cache_logradouro)

display(df_analise[['cep', 'bairro_informado', 'logradouro_api']].head(10))

display(df_analise.head(16))

             cep bairro_informado logradouro_api
0       71926750     Águas Claras    Rua Baracat
1       72140010     Águas Claras   Quadra QNJ 1
2       72140010       Taguatinga   Quadra QNJ 1
3       71929000     Águas Claras         Rua 28
4       00000000       Taguatinga  Não informado
5  Não informado     Águas Claras  Não informado
6  Não informado       Taguatinga  Não informado
7       72006400    Vicente Pires      Rua Rua 6
8       71926750     Águas Claras    Rua Baracat
9       71950000     Águas Claras    Quadra QS 1

,id_cliente,razao_social,cnpj,telefone,email,bairro_informado,cep,cidade,uf,data_cadastro,vendedor_responsavel,logradouro_api
0,CLI0001,Mercadinho Boa Vista,84959310341316,61970855700,contato@mercadinhobo.com.br,Águas Claras,71926750,Brasília,DF,2022-06-21,Bruno Almeida,Rua Baracat
1,CLI0002,Comercial São Judas,28327648350305,61953862084,contato@comercialsão.com.br,Águas Claras,72140010,Brasília,DF,2023-07-10,Camila Torres,Quadra QNJ 1
2,CLI0003,Armarinhos Silva & Cia,42388496965328,61924891771,contato@armarinhossi.com.br,Taguatinga,72140010,Brasília,DF,2022-02-28,Camila Torres,Quadra QNJ 1
3,CLI0004,Empório Vale Verde,69784801845146,61984331053,contato@empóriovalev.com.br,Águas Claras,71929000,Brasília,DF,2023-12-24,Diego Martins,Rua 28
4,CLI0005,Mercearia Dois Irmãos,89325288095701,61951273847,contato@merceariadoi.com.br,Taguatinga,00000000,Brasília,DF,2022-01-08,Diego Martins,Não informado
5,CLI0006,Casa das Tintas Ipê,82278248963834,61971188177,contato@casadastinta.com.br,Águas Claras,Não informado,Brasília,DF,2021-08-17,Camila Torres,Não informado
6,CLI0007,Distribuidora Popular Centro-Oeste,83930103105183,61999788677,contato@distribuidor.com.br,Taguatinga,Não informado,Brasília,DF,2025-04-16,Camila Torres,Não informado
7,CLI0008,Bazar Estrela Dourada,31165667010651,61941394116,contato@bazarestrela.com.br,Vicente Pires,72006400,Brasília,DF,2022-08-18,Juliana Reis,Rua Rua 6
8,CLI0009,Supermercado Nova Aliança,10801326773602,61910357396,contato@supermercado.com.br,Águas Claras,71926750,Brasília,DF,2023-09-08,Juliana Reis,Rua Baracat
9,CLI0010,Papelaria Horizonte,34309805009788,61919319320,contato@papelariahor.com.br,Águas Claras,71950000,Brasília,DF,2021-03-03,Diego Martins,Quadra QS 1
10,CLI0011,Ferragens União,93990916998543,61942035886,contato@ferragensuni.com.br,Vicente Pires,72006400,Brasília,DF,2022-09-07,Bruno Almeida,Rua Rua 6
11,CLI0012,Mercado Cantinho do Sabor,79911838425135,61931172421,contato@mercadocanti.com.br,Águas Claras,71950000,Brasília,DF,2023-09-15,Diego Martins,Quadra QS 1
12,CLI0013,Loja Fatima Confecções,24118244935348,61951141832,contato@lojafatimaco.com.br,Guará I,Não informado,Brasília,DF,2024-03-11,Bruno Almeida,Não informado
13,CLI0014,Depósito São Roque,27868011280598,61980413088,contato@depósitosãor.com.br,Taguatinga,Não informado,Brasília,DF,2023-05-02,Rafael Souza,Não informado
14,CLI0015,Comercial Rio Bonito,69232260256342,6134911634,contato@comercialrio.com.br,Águas Claras,71926750,Brasília,DF,2022-08-28,Camila Torres,Rua Baracat
15,CLI0016,Minimercado Vitória Régia,36541458685014,61953491626,contato@minimercadov.com.br,Vicente Pires,72006400,Brasília,DF,2024-04-10,Bruno Almeida,Rua Rua 6

### 🔍 Normalização Automática de Bairros (Fuzzy Matching)

Nesta etapa, automatizamos a padronização das Regiões Administrativas do Distrito Federal:

- **Comparação Aproximada (`difflib`):** Utiliza algoritmos de *fuzzy matching* para detetar e corrigir automaticamente erros de digitação e variações de escrita.
- **Lista Oficial de RAs:** Valida os dados informados contra a lista oficial completa com todas as 35 Regiões Administrativas do DF.
- **Tratamento Seguro:** Caso o texto seja totalmente desconhecido ou fora do padrão, o pipeline preserva a formatação original sem forçar correspondências incorretas.

In [ ]:

# Lista oficial com todas as Regiões Administrativas do Distrito Federal
bairros_oficiais = [
    "Plano Piloto", "Gama", "Taguatinga", "Brazlândia", "Sobradinho", 
    "Planaltina", "Paranoá", "Núcleo Bandeirante", "Ceilândia", "Guará", 
    "Cruzeiro", "Samambaia", "Santa Maria", "São Sebastião", "Recanto das Emas", 
    "Lago Sul", "Riacho Fundo", "Lago Norte", "Candangolândia", "Águas Claras", 
    "Riacho Fundo II", "Sudoeste/Octogonal", "Varjão", "Park Way", "SCIA", 
    "Sobradinho II", "Jardim Botânico", "Itapoã", "SIA", "Vicente Pires", 
    "Fercal", "Sol Nascente/Pôr do Sol", "Arniqueira", "Arapoanga", "Água Quente"
]